INSERT INTO scam_campaign_jobs (id, title, company, location, salary, snippet, contact_phone, contact_email, payment_id, source) VALUES
('scam-campaign-01', 'Remote Data Entry Assistant', 'FlexiWorks Global', 'Remote', '₹15,000 - ₹25,000 / month', 'Hiring remote workers for online data entry tasks. Must pay a one-time registration fee of ₹299 through UPI. Contact +91 98765 43210 or flexiworks.jobs@outlook.com. WhatsApp only. Initial onboarding via payment ID flexiworks.pay@oksbi.', '+91 98765 43210', 'flexiworks.jobs@outlook.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-02', 'Customer Support Executive', 'Nexa Careers', 'Remote', '₹18,000 - ₹30,000 / month', 'Immediate openings for work-from-home customer support. Selected candidates are expected to make a refundable deposit of ₹499. Contact +91 98765 43210, support@nexacareers.co.in, and UPI ID flexiworks.pay@oksbi. Join through WhatsApp messaging.', '+91 98765 43210', 'support@nexacareers.co.in', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-03', 'Social Media Evaluator', 'MetroReach Jobs', 'Remote', '₹12,000 - ₹22,000 / month', 'Part-time social media evaluator opportunity. Register with your mobile number and pay a small activation fee of ₹350. Reach us on +91 98765 43210 or hr@metroreachjobs.com. Payment reference: flexiworks.pay@oksbi.', '+91 98765 43210', 'hr@metroreachjobs.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-04', 'Online Form Filling Job', 'SkillBridge Hiring', 'Remote', '₹20,000 - ₹35,000 / month', 'No experience required. Submit your details to skillbridge.hiring@gmail.com and pay ₹650 for the training kit. Contact +91 98765 43210. UPI payment ID: flexiworks.pay@oksbi. Fast onboarding through WhatsApp.', '+91 98765 43210', 'skillbridge.hiring@gmail.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-05', 'Virtual Assistant - Work from Home', 'PrimeAssist Global', 'Remote', '₹16,000 - ₹28,000 / month', 'Need remote virtual assistants for basic admin work. Paid onboarding includes a ₹599 account activation charge. Send resume to primeassist.hr@gmail.com or WhatsApp +91 98765 43210. Payment to flexiworks.pay@oksbi.', '+91 98765 43210', 'primeassist.hr@gmail.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-06', 'Work From Home Typist', 'Allied Global Services', 'Remote', '₹14,000 - ₹24,000 / month', 'Urgent vacancies for home-based typist. Registration is quick and requires a ₹300 joining fee. Contact +91 98765 43210 or alliedjobs.hiring@outlook.com. Payment should be sent to UPI ID flexiworks.pay@oksbi. We will send the job letter by WhatsApp.', '+91 98765 43210', 'alliedjobs.hiring@outlook.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-07', 'Data Processing Operator', 'Zenith Hiring Desk', 'Remote', '₹17,000 - ₹26,000 / month', 'We are hiring online data processing operators. You have to pay ₹450 as verification fee before starting. Call +91 98765 43210 or email hiring@zenithdesk.in. Payment ID: flexiworks.pay@oksbi. Initial onboarding will be done on WhatsApp.', '+91 98765 43210', 'hiring@zenithdesk.in', 'flexiworks.pay@oksbi', 'local-scam-campaign-db'),
('scam-campaign-08', 'Remote Customer Service Agent', 'BrightPath Careers', 'Remote', '₹19,000 - ₹32,000 / month', 'BrightPath Careers is hiring remote customer service agents with no prior experience required. Pay a refundable security fee of ₹500 before activation. Contact +91 98765 43210, careers@brightpathjobs.com, or WhatsApp. UPI payment ID flexiworks.pay@oksbi.', '+91 98765 43210', 'careers@brightpathjobs.com', 'flexiworks.pay@oksbi', 'local-scam-campaign-db');
